//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScopoTracker.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public int CenterID { get; set; }
        public string CenterNo { get; set; }
        public string CenterName { get; set; }
    }
}
